### ISSUE TITLE
Question of the VA values in a 2s clip

### ISSUE THREAD

**Issue by kevinlin91** [linkAmy/IMEMNet#2]
Hi, thanks for the great work.
I have a question about DEAM dataset.
Since DEAM provides VA values by each 500 ms from the 15th second, how do you define the VA values for the each 2 second clips in your IMEMNet dataset.
For example, the clip 4-10 which represents the 18th - 20th second in Song 4.
There are 4 VA values in the clip 4-10 (sample_18000ms, sample_18500ms, sample_19000ms, sample_19500ms).
So, do you take the average of these 4 values?

**Comment by linkAmy** [comment]
Yes, we take the average.
